# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='body',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
