# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 15:35
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160731_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
