# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='body',
            new_name='content',
        ),
    ]
